import 'dart:io';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../models/seller_model.dart';
import '../services/seller_firestore_service.dart';
import 'seller_state.dart';

class SellerCubit extends Cubit<SellerState> {
  final SellerFirestoreService _firestoreService;

  SellerCubit(this._firestoreService) : super(const SellerInitial());

  // ─── Dashboard ───
  Future<void> loadDashboard() async {
    emit(const SellerLoading());
    try {
      final products = await _firestoreService.getProducts();
      final orders = await _firestoreService.getOrders();
      final stats = await _firestoreService.getDashboardStats();

      emit(SellerLoaded(
        products: products,
        orders: orders,
        stats: stats,
        activeOrderFilter: 'All',
        productSearchQuery: '',
      ));
    } catch (e) {
      emit(SellerError(e.toString()));
    }
  }

  // ─── Product Management ───
  void searchProducts(String query) {
    final current = state;
    if (current is SellerLoaded) {
      emit(current.copyWith(productSearchQuery: query));
    }
  }

  Future<void> toggleProductActive(String productId) async {
    final current = state;
    if (current is SellerLoaded) {
      try {
        final product = current.products.firstWhere((p) => p.id == productId);
        final updatedProduct = product.copyWith(isActive: !product.isActive);
        
        // Optimistic UI update
        _updateProductsInState(current, updatedProduct);
        
        // Update in Firestore
        await _firestoreService.updateProduct(updatedProduct);
      } catch (e) {
        // Handle error (could revert state or show message)
        emit(SellerError(e.toString()));
      }
    }
  }

  Future<void> deleteProduct(String productId) async {
    final current = state;
    if (current is SellerLoaded) {
      try {
        // Optimistic UI update
        final updatedProducts = current.products.where((p) => p.id != productId).toList();
        emit(current.copyWith(products: updatedProducts));
        
        // Update in Firestore
        await _firestoreService.deleteProduct(productId);
      } catch (e) {
        emit(SellerError(e.toString()));
      }
    }
  }

  Future<void> addProduct(SellerProductModel product) async {
    final current = state;
    if (current is SellerLoaded) {
      try {
        await _firestoreService.addProduct(product);
        await loadDashboard();
      } catch (e) {
        emit(SellerError(e.toString()));
      }
    }
  }

  Future<void> addProductWithImages({
    required String name,
    required String description,
    required double price,
    required int stock,
    required String category,
    required List<File> imageFiles,
  }) async {
    final current = state;
    if (current is SellerLoaded) {
      try {
        // We emit SellerLoading so the UI can show a progress indicator while uploading
        emit(const SellerLoading());
        
        // 1. Upload images to Firebase Storage
        List<String> imageUrls = [];
        if (imageFiles.isNotEmpty) {
          imageUrls = await _firestoreService.uploadProductImages(imageFiles);
        }

        // 2. Create the model
        final newProduct = SellerProductModel(
          id: '', // Will be generated by Firestore
          name: name,
          description: description,
          price: price,
          stock: stock,
          category: category,
          images: imageUrls,
          isActive: true,
          status: stock > 0 ? 'In Stock' : 'Out of Stock',
        );
        
        // 3. Save to Firestore
        await _firestoreService.addProduct(newProduct);
        
        // 4. Refresh dashboard to get newly added product with proper ID
        await loadDashboard();
      } catch (e) {
        print('⚠️ Storage upload failed, using placeholder images for testing: $e');
        
        // Use placeholder images to allow testing Firestore
        final testProduct = SellerProductModel(
          id: '', 
          name: name,
          description: description,
          price: price,
          stock: stock,
          category: category,
          images: ['https://via.placeholder.com/400'], // Placeholder image
          isActive: true,
          status: stock > 0 ? 'In Stock' : 'Out of Stock',
        );
        
        await _firestoreService.addProduct(testProduct);
        await loadDashboard();
        
        // Show a warning but don't stop the process
        emit(SellerLoaded(
          products: (state as SellerLoaded).products,
          orders: (state as SellerLoaded).orders,
          stats: (state as SellerLoaded).stats,
          activeOrderFilter: (state as SellerLoaded).activeOrderFilter,
          productSearchQuery: (state as SellerLoaded).productSearchQuery,
        ));
      }
    }
  }

  Future<void> updateProduct(SellerProductModel product) async {
    final current = state;
    if (current is SellerLoaded) {
      try {
        // Optimistic UI update
        _updateProductsInState(current, product);
        
        // Update in Firestore
        await _firestoreService.updateProduct(product);
      } catch (e) {
        emit(SellerError(e.toString()));
      }
    }
  }

  void _updateProductsInState(SellerLoaded current, SellerProductModel updatedProduct) {
    final updatedProducts = current.products.map((p) {
      if (p.id == updatedProduct.id) return updatedProduct;
      return p;
    }).toList();
    emit(current.copyWith(products: updatedProducts));
  }

  // ─── Order Management ───
  void filterOrders(String filter) {
    final current = state;
    if (current is SellerLoaded) {
      emit(current.copyWith(activeOrderFilter: filter));
    }
  }

  Future<void> updateOrderStatus(String orderId, String newStatus) async {
    final current = state;
    if (current is SellerLoaded) {
      try {
        // Optimistic UI update
        final updatedOrders = current.orders.map((o) {
          if (o.orderId == orderId) {
            return o.copyWith(status: newStatus);
          }
          return o;
        }).toList();
        emit(current.copyWith(orders: updatedOrders));
        
        // Update in Firestore
        await _firestoreService.updateOrderStatus(orderId, newStatus);
      } catch (e) {
        emit(SellerError(e.toString()));
      }
    }
  }

  // ─── Filtered getters ───
  List<SellerProductModel> get filteredProducts {
    final current = state;
    if (current is SellerLoaded) {
      if (current.productSearchQuery.isEmpty) return current.products;
      return current.products
          .where((p) => p.name
              .toLowerCase()
              .contains(current.productSearchQuery.toLowerCase()))
          .toList();
    }
    return [];
  }

  List<SellerOrderModel> get filteredOrders {
    final current = state;
    if (current is SellerLoaded) {
      if (current.activeOrderFilter == 'All') return current.orders;
      return current.orders
          .where((o) => o.status == current.activeOrderFilter)
          .toList();
    }
    return [];
  }
}
