// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf0OdL4K_VEQIgLvQOH8xMeV7LRGPHv8M',
    appId: '1:825459601482:web:342a33910609bcf217f6b3',
    messagingSenderId: '825459601482',
    projectId: 'ayady-b4737',
    authDomain: 'ayady-b4737.firebaseapp.com',
    storageBucket: 'ayady-b4737.firebasestorage.app',
    measurementId: 'G-HWN40LJN1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdPsObNEKqKDipyb4ji-xBnW_GjJ_jFk',
    appId: '1:825459601482:android:fa70618ad2d0d04417f6b3',
    messagingSenderId: '825459601482',
    projectId: 'ayady-b4737',
    storageBucket: 'ayady-b4737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufaroRHlQdiJswKsvoKcjINQyAR-AWHo',
    appId: '1:825459601482:ios:9d3c511899b75a4717f6b3',
    messagingSenderId: '825459601482',
    projectId: 'ayady-b4737',
    storageBucket: 'ayady-b4737.firebasestorage.app',
    iosBundleId: 'com.example.handmadeEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAufaroRHlQdiJswKsvoKcjINQyAR-AWHo',
    appId: '1:825459601482:ios:9d3c511899b75a4717f6b3',
    messagingSenderId: '825459601482',
    projectId: 'ayady-b4737',
    storageBucket: 'ayady-b4737.firebasestorage.app',
    iosBundleId: 'com.example.handmadeEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf0OdL4K_VEQIgLvQOH8xMeV7LRGPHv8M',
    appId: '1:825459601482:web:aaa96fdfe0b5448d17f6b3',
    messagingSenderId: '825459601482',
    projectId: 'ayady-b4737',
    authDomain: 'ayady-b4737.firebaseapp.com',
    storageBucket: 'ayady-b4737.firebasestorage.app',
    measurementId: 'G-WLY3B679H6',
  );
}
