// import 'dart:io';
// import 'dart:async';
// import 'package:cloud_firestore/cloud_firestore.dart';

// // Products data extracted from handmade_products_dataset.csv
// final List<Map<String, dynamic>> productsData = [
//   {
//     'name': 'Sunflower Shaped Handmade Candle',
//     'nameAR': 'شمعة عباد الشمس يدوية',
//     'description':
//         'A bright sunflower-shaped handmade candle that adds a warm and cheerful touch to cozy spaces.',
//     'descriptionAR':
//         'شمعة يدوية مشرقة على شكل عباد الشمس تضفي لمسة دافئة ومرحة للأماكن الدافئة.',
//     'price': 220.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777584256/p001_sunflower_shaped_candle.jpg_zrzbzt.jpg',
//     ],
//     'categoryId': 'candles',
//     'sellerId': '5kcakiIFlFQ3al96Bn50lKWumzu1',
//     'stock': 15,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'candle',
//       'sunflower',
//       'yellow',
//       'cheerful',
//       'floral',
//       'bedroom',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Blue Marble Jar Candle',
//     'nameAR': 'شمعة جرة رخامية زرقاء',
//     'description':
//         'A modern handmade jar candle with a blue marble effect, perfect for calm and elegant room decor.',
//     'descriptionAR':
//         'شمعة جرة يدوية حديثة بتأثير رخامي أزرق، مثالية لديكور الغرف الهادئة والأنيقة.',
//     'price': 260.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777584261/p002_blue_marble_jar_candle.jpg_a5fgga.jpg',
//     ],
//     'categoryId': 'candles',
//     'sellerId': '830H55teV7R37Hp0I7DqrDXmvg82',
//     'stock': 12,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'candle',
//       'jar_candle',
//       'marble',
//       'blue',
//       'white',
//       'modern',
//       'calm',
//     ],
//   },
//   {
//     'name': 'Pink Floral Gel Candle',
//     'nameAR': 'شمعة جل زهرية وردية',
//     'description':
//         'A romantic handmade gel candle with pink floral details, suitable for soft and feminine room decoration.',
//     'descriptionAR':
//         'شمعة جل يدوية رومانسية بتفاصيل زهرية وردية، مناسبة لديكور الغرف الناعم والأنثوي.',
//     'price': 350.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777584257/p003_pink_floral_gel_candle.jpg_fzc50b.jpg',
//     ],
//     'categoryId': 'candles',
//     'sellerId': 'ACtzBuCeZ5ciUQaIymhTjy9qYcY2',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'candle',
//       'gel_candle',
//       'floral',
//       'pink',
//       'romantic',
//       'girly',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Rose Flower Candle Set',
//     'nameAR': 'مجموعة شموع زهور الورد',
//     'description':
//         'A set of handmade rose-shaped candles in soft colors, ideal for romantic and cozy room styling.',
//     'descriptionAR':
//         'مجموعة شموع يدوية على شكل وردة بألوان ناعمة، مثالية لتنسيق الغرف الرومانسية والدافئة.',
//     'price': 300.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777584260/p004_rose_flower_candle_set.jpg_sz6vij.jpg',
//     ],
//     'categoryId': 'candles',
//     'sellerId': 'BOOSdaRXtSR89s6eSJlkFD7Tlfx1',
//     'stock': 14,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': ['candle', 'rose_candle', 'flower', 'pink', 'romantic', 'cozy'],
//   },
//   {
//     'name': 'Colorful Daisy Candle Bouquet',
//     'nameAR': 'باقة شموع الأقحوان الملونة',
//     'description':
//         'A colorful bouquet of handmade daisy candles, perfect as a decorative gift or bright room accessory.',
//     'descriptionAR':
//         'باقة ملونة من شموع الأقحوان اليدوية، مثالية كهدية تزيينية أو إكسسوار غرفة مشرق.',
//     'price': 420.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777584259/p005_colorful_daisy_candle_bouquet.jpg_ooeksi.jpg',
//     ],
//     'categoryId': 'candles',
//     'sellerId': 'CrRA0kX4WCSHQBHHs8Rz4W19FMD3',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'candle',
//       'daisy',
//       'bouquet',
//       'colorful',
//       'gift',
//       'floral',
//       'cheerful',
//     ],
//   },
//   {
//     'name': 'Dried Flower Glass Candle Set',
//     'nameAR': 'مجموعة شموع زجاجية بالزهور المجففة',
//     'description':
//         'A soft glass candle set decorated with dried flowers, suitable for minimal and relaxing spaces.',
//     'descriptionAR':
//         'مجموعة شموع زجاجية ناعمة مزينة بالزهور المجففة، مناسبة للمساحات البسيطة والمريحة.',
//     'price': 280.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777584258/p006_dried_flower_glass_candle_set.jpg_apc6ii.jpg',
//     ],
//     'categoryId': 'candles',
//     'sellerId': 'EIDWxWZ2l9uxTTPYUx4U',
//     'stock': 16,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'candle',
//       'glass_candle',
//       'dried_flowers',
//       'pink',
//       'white',
//       'minimal',
//       'calm',
//     ],
//   },
//   {
//     'name': 'Marble Ceramic Tray Set',
//     'nameAR': 'مجموعة صواني سيراميك رخامية',
//     'description':
//         'A handmade marble-style ceramic tray set suitable for jewelry, candles, and elegant room decoration.',
//     'descriptionAR':
//         'مجموعة صواني سيراميك رخامية يدوية مناسبة للمجوهرات والشموع وديكور الغرف الأنيقة.',
//     'price': 380.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586088/p007_marble_ceramic_tray_set.jpg_ujc06r.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'F15IoVsFGIgFyYsRf2hvAGaLsIo2',
//     'stock': 11,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': ['ceramic', 'tray', 'marble', 'white', 'gray', 'black', 'modern'],
//   },
//   {
//     'name': 'Pastel Bubble Vase Set',
//     'nameAR': 'مجموعة مزهرية وفازات باستيل فقاعية',
//     'description':
//         'A cute pastel ceramic vase and tray set with a soft bubble design, perfect for feminine and cozy spaces.',
//     'descriptionAR':
//         'مجموعة فازات وصواني سيراميك باستيل لطيفة بتصميم فقاعي ناعم، مثالية للمساحات الأنثوية والدافئة.',
//     'price': 520.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586081/p008_pastel_bubble_vase_set.jpg_gnjb1m.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'FIJdLk2QExdW5KJbVDjDBU2BBr83',
//     'stock': 9,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'vase',
//       'tray',
//       'pastel',
//       'pink',
//       'white',
//       'soft',
//       'cute',
//     ],
//   },
//   {
//     'name': 'Minimal Black White Vase Set',
//     'nameAR': 'مجموعة فازات أسود أبيض بسيطة',
//     'description':
//         'A minimal handmade ceramic vase set in neutral colors, suitable for modern shelves and table decor.',
//     'descriptionAR':
//         'مجموعة فازات سيراميك يدوية بألوان محايدة، مناسبة للرفوف الحديثة وديكور الطاولات.',
//     'price': 480.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586088/p009_minimal_black_white_vase_set.jpg_tgqcog.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'I949AxC7d2Q5dkfyAQOI',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.6,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': ['ceramic', 'vase', 'black', 'white', 'beige', 'minimal', 'modern'],
//   },
//   {
//     'name': 'Boho Shell Ceramic Vase',
//     'nameAR': 'مزهرية سيراميك بوهو بطلاء الصدف',
//     'description':
//         'A boho handmade ceramic vase with shell-inspired details, ideal for dried flowers and natural room styling.',
//     'descriptionAR':
//         'مزهرية سيراميك يدوية بوهو بتفاصيل مستوحاة من الصدف، مثالية للزهور المجففة وتنسيق الغرف الطبيعي.',
//     'price': 430.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586081/p010_boho_shell_ceramic_vase.jpg_ucidut.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'ML5aMvdvnu7McFoiyold',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'vase',
//       'shell',
//       'boho',
//       'white',
//       'beige',
//       'dried_flowers',
//     ],
//   },
//   {
//     'name': 'Feather Ceramic Tray Set',
//     'nameAR': 'مجموعة صواني سيراميك ريش',
//     'description':
//         'A handmade feather-shaped ceramic tray set for jewelry, accessories, and elegant table decoration.',
//     'descriptionAR':
//         'مجموعة صواني سيراميك يدوية على شكل ريش للمجوهرات والإكسسوارات وديكور الطاولات الأنيقة.',
//     'price': 360.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586083/p011_feather_ceramic_tray_set.jpg_dj83hv.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'TqLQoWZAfawfkewvGD0X',
//     'stock': 12,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'tray',
//       'feather',
//       'gold',
//       'white',
//       'elegant',
//       'jewelry_tray',
//     ],
//   },
//   {
//     'name': 'White Shell Tray Vase Set',
//     'nameAR': 'مجموعة صواني وفازات بطلاء الصدف الأبيض',
//     'description':
//         'A white shell-inspired ceramic tray and vase set that gives a calm coastal touch to small spaces.',
//     'descriptionAR':
//         'مجموعة صواني وفازات سيراميك مستوحاة من الصدف الأبيض تمنح لمسة ساحلية هادئة للمساحات الصغيرة.',
//     'price': 470.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586088/p012_white_shell_tray_vase_set.jpg_p4dnwv.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'buDpekfFigv5KzMfeyHq',
//     'stock': 7,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.6,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'shell',
//       'tray',
//       'vase',
//       'white',
//       'blue',
//       'coastal',
//       'calm',
//     ],
//   },
//   {
//     'name': 'Black Gold Ceramic Decor Set',
//     'nameAR': 'مجموعة ديكور سيراميك أسود وذهبي',
//     'description':
//         'A luxury black and gold ceramic decor set suitable for modern living rooms and office spaces.',
//     'descriptionAR':
//         'مجموعة ديكور سيراميك فاخرة باللونين الأسود والذهبي، مناسبة لغرف المعيشة الحديثة ومساحات المكاتب.',
//     'price': 650.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586088/p013_black_gold_ceramic_decor_set.jpg_rryq7a.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'dE62YTlv5A86SSG3sg07',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'decor_set',
//       'black',
//       'gold',
//       'modern',
//       'luxury',
//       'table_decor',
//     ],
//   },
//   {
//     'name': 'Small Daisy Ceramic Vase',
//     'nameAR': 'مزهرية سيراميك أقحوان صغيرة',
//     'description':
//         'A small textured ceramic daisy vase, perfect for tiny flowers, desks, and cozy room corners.',
//     'descriptionAR':
//         'مزهرية سيراميك يدوية صغيرة ذات ملمس نسيجي، مثالية للزهور الصغيرة والمكاتب وزوايا الغرف الدافئة.',
//     'price': 290.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586096/p014_small_daisy_ceramic_vase.jpg_tbjuj7.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'gvik0mzRmKsHFBm6E4qq',
//     'stock': 14,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': ['ceramic', 'vase', 'daisy', 'white', 'boho', 'small_room', 'cozy'],
//   },
//   {
//     'name': 'Pink Textured Ceramic Vase',
//     'nameAR': 'مزهرية سيراميك وردية بنسيج نسيجي',
//     'description':
//         'A pink textured handmade ceramic vase with a soft romantic look, ideal for flowers and bedroom decor.',
//     'descriptionAR':
//         'مزهرية سيراميك يدوية وردية بنسيج نسيجي بمظهر رومانسي ناعم، مثالية للزهور وديكور غرف النوم.',
//     'price': 340.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586095/p015_pink_textured_ceramic_vase.jpg_rqokdh.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'hO5qdnh32hPNOeKD7piv0f6Vodf1',
//     'stock': 13,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'vase',
//       'pink',
//       'textured',
//       'romantic',
//       'flower_vase',
//       'feminine',
//     ],
//   },
//   {
//     'name': 'Dotted Ceramic Decor Set',
//     'nameAR': 'مجموعة ديكور سيراميك منقط',
//     'description':
//         'A playful dotted ceramic decor set in neutral colors, suitable for shelves, desks, and cozy room styling.',
//     'descriptionAR':
//         'مجموعة ديكور سيراميك يدوية مرحة منقطة بألوان محايدة، مناسبة للرفوف والمكاتب وتنسيق الغرف الدافئة.',
//     'price': 390.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586092/p016_dotted_ceramic_decor_set.jpg_qqqo5f.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'hd9VKkCz5VUGI9Lq923D',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.6,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'dotted',
//       'decor_set',
//       'cream',
//       'beige',
//       'playful',
//       'shelf_decor',
//     ],
//   },
//   {
//     'name': 'Pastel Ceramic Donut Vases',
//     'nameAR': 'مجموعة فازات دونات سيراميك باستيل',
//     'description':
//         'A colorful pastel ceramic donut vase set that adds a fun handmade touch to bright and cheerful rooms.',
//     'descriptionAR':
//         'مجموعة فازات دونات سيراميك بألوان باستيل ملونة تضيف لمسة يدوية مرحة للغرف المشرقة والمرحة.',
//     'price': 440.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586096/p017_pastel_ceramic_donut_vases.jpg_vxd1nq.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'knx1uE0jM0SoVCTwBFZKZQWJtj73',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'donut_vase',
//       'pastel',
//       'colorful',
//       'pink',
//       'yellow',
//       'mint',
//       'fun',
//     ],
//   },
//   {
//     'name': 'Neutral Mini Vase Set',
//     'nameAR': 'مجموعة فازات مصغرة محايدة',
//     'description':
//         'A neutral mini ceramic vase set for simple shelves, bathrooms, desks, and minimal room decoration.',
//     'descriptionAR':
//         'مجموعة فازات سيراميك مصغرة محايدة للرفوف البسيطة والحمامات والمكاتب وديكور الغرف البسيط.',
//     'price': 330.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586097/p018_neutral_mini_vase_set.jpg_i2ifan.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'nUhVB1X8zR2UdBZcKaZS',
//     'stock': 15,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'mini_vase',
//       'neutral',
//       'cream',
//       'beige',
//       'minimal',
//       'bathroom',
//     ],
//   },
//   {
//     'name': 'Black Beige Ceramic Vase Tray',
//     'nameAR': 'مجموعة فاز وصينية سيراميك أسود وبيج',
//     'description':
//         'An elegant black and beige handmade ceramic vase with tray, suitable for modern table and shelf styling.',
//     'descriptionAR':
//         'مزهرية وصينية سيراميك يدوية باللونين الأسود والبيج، مناسبة لتنسيق الطاولات والرفوف الحديثة.',
//     'price': 410.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586098/p019_black_beige_ceramic_vase_tray.jpg_eyy9hy.jpg',
//     ],
//     'categoryId': 'ceramic_vases',
//     'sellerId': 'p8zKpWHdKOXv4DFlqLc23WyoG8T2',
//     'stock': 9,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'ceramic',
//       'vase',
//       'tray',
//       'black',
//       'beige',
//       'gold',
//       'elegant',
//       'modern',
//     ],
//   },
//   {
//     'name': 'Boho Macrame Cotton Curtain',
//     'nameAR': 'ستارة قطنية ماكريميه بوهو',
//     'description':
//         'A handmade boho macrame cotton curtain suitable for doors, windows, and cozy room decoration.',
//     'descriptionAR':
//         'ستارة قطنية ماكريميه يدوية بوهو مناسبة للأبواب والنوافذ وديكور الغرف الدافئة.',
//     'price': 620.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586778/p020_boho_macrame_cotton_curtain.jpg_bk71mi.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 't8inhihNJMetEAc12qatmJI0Vwg1',
//     'stock': 7,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'curtain',
//       'boho',
//       'cotton',
//       'beige',
//       'cream',
//       'door_decor',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Large Macrame Wall Hanging',
//     'nameAR': 'تعليقة حائط ماكريميه كبيرة',
//     'description':
//         'A large handmade macrame wall hanging that adds a warm boho touch to bedrooms and living rooms.',
//     'descriptionAR':
//         'تعليقة حائط ماكريميه يدوية كبيرة تضيف لمسة بوهو دافئة لغرف النوم وغرف المعيشة.',
//     'price': 780.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586778/p021_large_macrame_wall_hanging.jpg_ckccl6.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'vyOn3H6WviNK4H1sjx5Jts7XxWu2',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'wall_hanging',
//       'boho',
//       'cream',
//       'beige',
//       'wall_decor',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Beige Macrame Wall Decor',
//     'nameAR': 'ديكور حائط ماكريميه بيج',
//     'description':
//         'A simple beige macrame wall decor piece suitable for small cozy spaces and neutral interiors.',
//     'descriptionAR':
//         'قطعة ديكور حائط ماكريميه يدوية بيج بسيطة مناسبة للمساحات الصغيرة الدافئة والديكورات الداخلية المحايدة.',
//     'price': 540.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586781/p022_beige_macrame_wall_decor.jpg_qhqatj.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'zUINEDl7j1td6H92yqbZ',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'wall_decor',
//       'beige',
//       'white',
//       'boho',
//       'neutral',
//       'cozy',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Wide Macrame Wall Hanging',
//     'nameAR': 'تعليقة حائط ماكريميه عريضة',
//     'description':
//         'A wide handmade macrame wall hanging designed for large walls and natural room styling.',
//     'descriptionAR':
//         'تعليقة حائط ماكريميه يدوية عريضة مصممة للجدران الكبيرة وتنسيق الغرف الطبيعي.',
//     'price': 850.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586781/p023_wide_macrame_wall_hanging.jpg_z92rdz.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': '5kcakiIFlFQ3al96Bn50lKWumzu1',
//     'stock': 5,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'wide_wall_hanging',
//       'cream',
//       'beige',
//       'natural',
//       'large_room',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Framed Macrame Wall Art',
//     'nameAR': 'لوحة حائط ماكريميه مؤطرة',
//     'description':
//         'A framed handmade macrame wall art piece that combines cotton rope and wood for a natural look.',
//     'descriptionAR':
//         'لوحة حائط ماكريميه يدوية مؤطرة تجمع بين حبل القطن والخشب لمظهر طبيعي.',
//     'price': 690.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586786/p024_framed_macrame_wall_art.jpg_kuqgc7.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': '830H55teV7R37Hp0I7DqrDXmvg82',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'framed_art',
//       'wall_art',
//       'cotton',
//       'wood',
//       'cream',
//       'natural',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Wall Mirror Leaves',
//     'nameAR': 'مرآة حائط ماكريميه بأوراق',
//     'description':
//         'A boho macrame wall mirror with hanging leaf details, perfect for soft and decorative spaces.',
//     'descriptionAR':
//         'مرآة حائط ماكريميه بوهو بتفاصيل أوراق معلقة، مثالية للمساحات الناعمة والديكوراتية.',
//     'price': 720.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586788/p025_macrame_wall_mirror_leaves.jpg_bzkjrp.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'ACtzBuCeZ5ciUQaIymhTjy9qYcY2',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'mirror',
//       'wall_mirror',
//       'leaves',
//       'boho',
//       'cream',
//       'handmade',
//       'decor',
//     ],
//   },
//   {
//     'name': 'Macrame Table Runner',
//     'nameAR': 'جريدة طاولة ماكريميه',
//     'description':
//         'A handmade macrame table runner suitable for dining tables, coffee tables, and natural home styling.',
//     'descriptionAR':
//         'جريدة طاولة ماكريميه يدوية مناسبة لطاولات الطعام وطاولات القهوة وتنسيق المنازل الطبيعي.',
//     'price': 460.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586794/p026_macrame_table_runner.jpg_slinyn.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'BOOSdaRXtSR89s6eSJlkFD7Tlfx1',
//     'stock': 11,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.6,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'table_runner',
//       'cotton',
//       'cream',
//       'beige',
//       'natural',
//       'dining_room',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Plant Hanger',
//     'nameAR': 'معلق نباتات ماكريميه',
//     'description':
//         'A handmade macrame plant hanger that adds a fresh boho touch to balconies and indoor plants.',
//     'descriptionAR':
//         'معلق نباتات ماكريميه يدوي يضيف لمسة بوهو طازجة للشرفات والنباتات الداخلية.',
//     'price': 390.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586799/p027_macrame_plant_hanger.jpg_wsy5eb.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'CrRA0kX4WCSHQBHHs8Rz4W19FMD3',
//     'stock': 13,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'plant_hanger',
//       'boho',
//       'cream',
//       'beige',
//       'balcony',
//       'plant_decor',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Swing Chair',
//     'nameAR': 'كرسي أرجوحة ماكريميه',
//     'description':
//         'A handmade macrame swing chair suitable for balconies, cozy corners, and relaxed boho interiors.',
//     'descriptionAR':
//         'كرسي أرجوحة ماكريميه يدوي مناسب للشرفات وزوايا الدفيء والديكورات الداخلية البوهو المريحة.',
//     'price': 1200.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586801/p028_macrame_swing_chair.jpg_t5flnp.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'EIDWxWZ2l9uxTTPYUx4U',
//     'stock': 4,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'swing_chair',
//       'boho',
//       'cream',
//       'beige',
//       'balcony',
//       'cozy_corner',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Round Macrame Mirror',
//     'nameAR': 'مرآة ماكريميه دائرية',
//     'description':
//         'A round handmade macrame mirror that works well as a soft boho wall accent.',
//     'descriptionAR': 'مرآة ماكريميه يدوية دائرية تعمل كلمسة بوهو ناعمة للحائط.',
//     'price': 680.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586800/p029_round_macrame_mirror.jpg_xhwn3a.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'F15IoVsFGIgFyYsRf2hvAGaLsIo2',
//     'stock': 7,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'round_mirror',
//       'mirror',
//       'boho',
//       'cream',
//       'beige',
//       'wall_decor',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Baby Swing',
//     'nameAR': 'أرجوحة أطفال ماكريميه',
//     'description':
//         'A soft handmade macrame baby swing designed as a decorative and cozy kids room piece.',
//     'descriptionAR':
//         'أرجوحة أطفال ماكريميه يدوية ناعمة مصممة كقطعة ديكور ودفيء لغرف الأطفال.',
//     'price': 950.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586807/p030_macrame_baby_swing.jpg_c37hky.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'FIJdLk2QExdW5KJbVDjDBU2BBr83',
//     'stock': 5,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'baby_swing',
//       'kids_room',
//       'cream',
//       'beige',
//       'soft',
//       'cozy',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Hanging Lamp',
//     'nameAR': 'مصباح معلق ماكريميه',
//     'description':
//         'A handmade macrame hanging lamp that creates warm lighting and a cozy boho atmosphere.',
//     'descriptionAR':
//         'مصباح معلق ماكريميه يدوي يخلق إضاءة دافئة وجواً بوهو دافئ.',
//     'price': 740.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586807/p031_macrame_hanging_lamp.jpg_b25les.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'I949AxC7d2Q5dkfyAQOI',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'hanging_lamp',
//       'lamp',
//       'lighting',
//       'boho',
//       'cream',
//       'cozy',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Bed Throw',
//     'nameAR': 'غطاء سرير ماكريميه',
//     'description':
//         'A handmade macrame bed throw that adds texture and a natural handmade look to bedroom styling.',
//     'descriptionAR':
//         'غطاء سرير ماكريميه يدوي يضيف نسيجاً ومظهراً يدوياً طبيعياً لتنسيق غرف النوم.',
//     'price': 880.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586816/p032_macrame_bed_throw.jpg_mp1fu7.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'ML5aMvdvnu7McFoiyold',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'bed_throw',
//       'bedroom',
//       'cotton',
//       'cream',
//       'beige',
//       'natural',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Cushion Cover',
//     'nameAR': 'غطاء وسادة ماكريميه',
//     'description':
//         'A handmade macrame cushion cover suitable for sofas, beds, and cozy boho room decoration.',
//     'descriptionAR':
//         'غطاء وسادة ماكريميه يدوي مناسب للأرائك والأسرة وديكور غرف البوهو الدافئة.',
//     'price': 350.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586820/p033_macrame_cushion_cover.jpg_wqsbwc.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'TqLQoWZAfawfkewvGD0X',
//     'stock': 14,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.6,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'cushion_cover',
//       'pillow',
//       'boho',
//       'cream',
//       'beige',
//       'sofa_decor',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Macrame Plant Wall Hanger',
//     'nameAR': 'معلق نباتات حائط ماكريميه',
//     'description':
//         'A handmade macrame plant wall hanger for displaying small plants in a fresh natural style.',
//     'descriptionAR':
//         'معلق نباتات حائط ماكريميه يدوي لعرض النباتات الصغيرة بأسلوب طبيعي طازج.',
//     'price': 520.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777586817/p034_macrame_plant_wall_hanger.jpg_u39j9j.jpg',
//     ],
//     'categoryId': 'macrame',
//     'sellerId': 'buDpekfFigv5KzMfeyHq',
//     'stock': 9,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'macrame',
//       'plant_wall_hanger',
//       'plant_decor',
//       'cream',
//       'green',
//       'boho',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Butterfly Wooden Wall Shelf',
//     'nameAR': 'رف حائط خشبي على شكل فراشة',
//     'description':
//         'A butterfly-shaped wooden wall shelf that adds a playful handmade touch to bedrooms and kids rooms.',
//     'descriptionAR':
//         'رف حائط خشبي يدوي على شكل فراشة يضيف لمسة يدوية مرحة لغرف النوم وغرف الأطفال.',
//     'price': 750.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588205/p035_butterfly_wooden_wall_shelf.jpg_rgoqmm.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'dE62YTlv5A86SSG3sg07',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'butterfly',
//       'wall_shelf',
//       'yellow',
//       'brown',
//       'playful',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'White Corner Wooden Shelf',
//     'nameAR': 'رف زاوية خشبي أبيض',
//     'description':
//         'A white corner wooden shelf suitable for organizing small decor pieces, candles, and plants.',
//     'descriptionAR':
//         'رف زاوية خشبي أبيض يدوي مناسب لتنظيم قطع الديكور الصغيرة والشموع والنباتات.',
//     'price': 620.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588207/p036_white_corner_wooden_shelf.jpg_abtfv9.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'gvik0mzRmKsHFBm6E4qq',
//     'stock': 9,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'corner_shelf',
//       'white',
//       'beige',
//       'minimal',
//       'bathroom',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Rustic Floating Wooden Shelves',
//     'nameAR': 'رفوف خشبية عائمة ريفية',
//     'description':
//         'A rustic floating wooden shelf set for displaying plants, books, and handmade home accessories.',
//     'descriptionAR':
//         'مجموعة رفوف خشبية عائمة ريفية يدوية لعرض النباتات والكتب وإكسسوارات المنازل اليدوية.',
//     'price': 680.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588209/p037_rustic_floating_wooden_shelves.jpg_xhjeb3.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'hO5qdnh32hPNOeKD7piv0f6Vodf1',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'floating_shelves',
//       'rustic',
//       'brown',
//       'black',
//       'kitchen',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Plant Corner Wooden Shelf',
//     'nameAR': 'رف زاوية نباتات خشبي',
//     'description':
//         'A corner wooden plant shelf designed for displaying indoor plants and creating a fresh natural room look.',
//     'descriptionAR':
//         'رف زاوية نباتات خشبي يدوي مصمم لعرض النباتات الداخلية وخلق مظهر غرف طبيعي طازج.',
//     'price': 720.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588214/p038_plant_corner_wooden_shelf.jpg_ktzrkv.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'hd9VKkCz5VUGI9Lq923D',
//     'stock': 7,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'plant_shelf',
//       'corner_shelf',
//       'black',
//       'brown',
//       'green',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Vertical Wall Wooden Shelves',
//     'nameAR': 'رفوف حائط خشبية عمودية',
//     'description':
//         'A vertical handmade wooden wall shelf set that works well for books, small plants, and decor pieces.',
//     'descriptionAR':
//         'مجموعة رفوف حائط خشبية عمودية يدوية تعمل جيداً للكتب والنباتات الصغيرة وقطع الديكور.',
//     'price': 640.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588215/p039_vertical_wall_wooden_shelves.jpg_cvxzu3.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'knx1uE0jM0SoVCTwBFZKZQWJtj73',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'vertical_shelf',
//       'wall_shelf',
//       'brown',
//       'black',
//       'modern',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Tree Shape Wooden Shelf',
//     'nameAR': 'رف خشبي على شكل شجرة',
//     'description':
//         'A tree-shaped wooden shelf that adds a warm natural look and provides space for small decor items.',
//     'descriptionAR':
//         'رف خشبي يدوي على شكل شجرة يضيف مظهراً طبيعياً دافئاً ويوفر مساحة لقطع الديكور الصغيرة.',
//     'price': 850.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588219/p040_tree_shape_wooden_shelf.jpg_ygwtnj.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'nUhVB1X8zR2UdBZcKaZS',
//     'stock': 5,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'tree_shelf',
//       'brown',
//       'beige',
//       'natural',
//       'kids_room',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Round Wooden Display Shelf',
//     'nameAR': 'رف عرض خشبي دائري',
//     'description':
//         'A round wooden display shelf suitable for books, vases, candles, and vintage-style room decoration.',
//     'descriptionAR':
//         'رف عرض خشبي دائري يدوي مناسب للكتب والمزهريات والشموع وديكور الغرف بأسلوب复古.',
//     'price': 780.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588220/p041_round_wooden_display_shelf.jpg_tk5viw.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'p8zKpWHdKOXv4DFlqLc23WyoG8T2',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'round_shelf',
//       'display_shelf',
//       'brown',
//       'black',
//       'vintage',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Abstract Wall Wooden Shelf',
//     'nameAR': 'رف حائط خشبي تجريدي',
//     'description':
//         'An abstract handmade wooden wall shelf that adds artistic style and practical display space.',
//     'descriptionAR':
//         'رف حائط خشبي يدوي تجريدي يضيف أسلوباً فنياً ومساحة عرض عملية.',
//     'price': 690.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588225/p042_abstract_wall_wooden_shelf.jpg_jbkh0l.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 't8inhihNJMetEAc12qatmJI0Vwg1',
//     'stock': 7,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'abstract_shelf',
//       'wall_shelf',
//       'brown',
//       'black',
//       'modern',
//       'artistic',
//     ],
//   },
//   {
//     'name': 'Giraffe Wooden Shelf',
//     'nameAR': 'رف خشبي على شكل زرافة',
//     'description':
//         'A giraffe-shaped wooden shelf designed for playful kids rooms and creative handmade decoration.',
//     'descriptionAR':
//         'رف خشبي يدوي على شكل زرافة مصمم لغرف الأطفال المرحة والديكورات اليدوية الإبداعية.',
//     'price': 760.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588227/p043_giraffe_wooden_shelf.jpg_byqvwg.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'vyOn3H6WviNK4H1sjx5Jts7XxWu2',
//     'stock': 5,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'giraffe',
//       'animal_shelf',
//       'brown',
//       'beige',
//       'playful',
//       'kids_room',
//     ],
//   },
//   {
//     'name': 'Balloon Wooden Wall Shelf',
//     'nameAR': 'رف حائط خشبي على شكل بالون',
//     'description':
//         'A balloon-shaped wooden wall shelf that gives a soft decorative touch to kids rooms and bedrooms.',
//     'descriptionAR':
//         'رف حائط خشبي يدوي على شكل بالون يمنح لمسة ديكور ناعمة لغرف الأطفال وغرف النوم.',
//     'price': 710.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588232/p044_balloon_wooden_wall_shelf.jpg_juljow.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': 'zUINEDl7j1td6H92yqbZ',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'balloon_shelf',
//       'wall_shelf',
//       'brown',
//       'beige',
//       'white',
//       'soft',
//       'kids_room',
//     ],
//   },
//   {
//     'name': 'Swan Wooden Display Shelf',
//     'nameAR': 'رف عرض خشبي على شكل بجعة',
//     'description':
//         'An elegant swan-shaped wooden display shelf for books, toys, and decorative handmade pieces.',
//     'descriptionAR':
//         'رف عرض خشبي يدوي أنيق على شكل بجعة للكتب والألعاب وقطع الديكور اليدوية.',
//     'price': 820.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588233/p045_swan_wooden_display_shelf.jpg_wg3h7l.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': '5kcakiIFlFQ3al96Bn50lKWumzu1',
//     'stock': 4,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'swan_shelf',
//       'display_shelf',
//       'white',
//       'beige',
//       'elegant',
//       'kids_room',
//     ],
//   },
//   {
//     'name': 'Kitchen Wooden Wall Shelves',
//     'nameAR': 'رفوف حائط خشبية للمطبخ',
//     'description':
//         'A rustic wooden wall shelf set suitable for kitchen organization, plants, and cozy home decor.',
//     'descriptionAR':
//         'مجموعة رفوف حائط خشبية ريفية مناسبة لتنظيم المطبخ والنباتات وديكور المنازل الدافئ.',
//     'price': 590.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588239/p046_kitchen_wooden_wall_shelves.jpg_o22u6h.jpg',
//     ],
//     'categoryId': 'wooden_shelves',
//     'sellerId': '830H55teV7R37Hp0I7DqrDXmvg82',
//     'stock': 11,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'wooden_shelf',
//       'kitchen_shelf',
//       'wall_shelf',
//       'brown',
//       'green',
//       'rustic',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Clay House Table Lamp',
//     'nameAR': 'مصباح طاولة منزلي طيني',
//     'description':
//         'A handmade clay house table lamp that gives warm lighting and adds a cozy decorative touch to the room.',
//     'descriptionAR':
//         'مصباح طاولة منزلي طيني يدوي يمنح إضاءة دافئة ولمسة ديكور دافئة للغرفة.',
//     'price': 620.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588968/p047_clay_house_table_lamp.jpg_mnms6r.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'ACtzBuCeZ5ciUQaIymhTjy9qYcY2',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'table_lamp',
//       'clay',
//       'house_lamp',
//       'warm',
//       'cozy',
//       'white',
//       'beige',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Mushroom Study Table Lamp',
//     'nameAR': 'مصباح مكتب على شكل فطر',
//     'description':
//         'A cute mushroom-style study lamp suitable for desks, bedside tables, and soft room lighting.',
//     'descriptionAR':
//         'مصباح مكتب لطيف على شكل فطر مناسب للمكاتب وطاولات السرير وإضاءة الغرف الناعمة.',
//     'price': 540.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588969/p048_mushroom_study_table_lamp.jpg_dzemco.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'BOOSdaRXtSR89s6eSJlkFD7Tlfx1',
//     'stock': 12,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'mushroom_lamp',
//       'study_lamp',
//       'cream',
//       'yellow',
//       'minimal',
//       'desk_lamp',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Deer Moon Table Lamp',
//     'nameAR': 'مصباح طاولة غزال وقمر',
//     'description':
//         'An elegant deer and moon table lamp that creates a soft magical atmosphere for cozy spaces.',
//     'descriptionAR':
//         'مصباح طاولة أنيق بغزال وقمر يخلق جواً سحرياً ناعماً للمساحات الدافئة.',
//     'price': 680.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588973/p049_deer_moon_table_lamp.jpg_dsszdt.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'CrRA0kX4WCSHQBHHs8Rz4W19FMD3',
//     'stock': 7,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'deer_lamp',
//       'moon_lamp',
//       'white',
//       'gold',
//       'elegant',
//       'cozy',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Duck Night Light Lamp',
//     'nameAR': 'مصباح ليلي على شكل بطة',
//     'description':
//         'A cute duck night light lamp suitable for kids rooms, bedside tables, and calm night lighting.',
//     'descriptionAR':
//         'مصباح ليلي لطيف على شكل بطة مناسب لغرف الأطفال وطاولات السرير وإضاءة الليل الهادئة.',
//     'price': 450.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588975/p050_duck_night_light_lamp.jpg_wvacfd.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'EIDWxWZ2l9uxTTPYUx4U',
//     'stock': 14,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'duck_lamp',
//       'night_light',
//       'yellow',
//       'orange',
//       'cute',
//       'kids_room',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Cute Ghost Night Lamp Set',
//     'nameAR': 'مجموعة مصابيح ليلية على شكل أشباح لطيفة',
//     'description':
//         'A set of cute ghost-shaped night lamps that adds playful warm lighting to bedrooms and kids rooms.',
//     'descriptionAR':
//         'مجموعة مصابيح ليلية على شكل أشباح لطيفة تضيف إضاءة دافئة مرحة لغرف النوم وغرف الأطفال.',
//     'price': 580.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588978/p051_cute_ghost_night_lamp_set.jpg_zn5xzk.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'F15IoVsFGIgFyYsRf2hvAGaLsIo2',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'ghost_lamp',
//       'night_lamp',
//       'white',
//       'yellow',
//       'cute',
//       'kids_room',
//       'playful',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Butterfly Table Lamp',
//     'nameAR': 'مصباح طاولة على شكل فراشة',
//     'description':
//         'A colorful butterfly table lamp that gives a bright decorative glow and a cheerful handmade look.',
//     'descriptionAR':
//         'مصباح طاولة ملون على شكل فراشة يمنح توهجاً ديكورياً مشرقاً ومظهراً يدوياً مرحاً.',
//     'price': 720.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588985/p052_butterfly_table_lamp.jpg_ehdmeq.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'FIJdLk2QExdW5KJbVDjDBU2BBr83',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.9,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'butterfly_lamp',
//       'table_lamp',
//       'orange',
//       'black',
//       'yellow',
//       'colorful',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Elephant Moon Table Lamp',
//     'nameAR': 'مصباح طاولة فيل وقمر',
//     'description':
//         'A soft elephant and moon table lamp that adds gentle lighting and a dreamy touch to the room.',
//     'descriptionAR':
//         'مصباح طاولة ناعم بفيل وقمر يضيف إضاءة لطيفة ولمسة حالمة للغرفة.',
//     'price': 690.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588984/p053_elephant_moon_table_lamp.jpg_osecem.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'I949AxC7d2Q5dkfyAQOI',
//     'stock': 8,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'elephant_lamp',
//       'moon_lamp',
//       'white',
//       'gold',
//       'soft',
//       'dreamy',
//       'kids_room',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Leaf Paper Table Lamp',
//     'nameAR': 'مصباح طاولة ورق بأوراق',
//     'description':
//         'A handmade paper table lamp with leaf cutout details, perfect for warm natural lighting and cozy decor.',
//     'descriptionAR':
//         'مصباح طاولة ورق يدوي بتفاصيل قص أوراق، مثالي للإضاءة الطبيعية الدافئة والديكور الدافئ.',
//     'price': 610.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588989/p054_leaf_paper_table_lamp.jpg_a1en5a.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'ML5aMvdvnu7McFoiyold',
//     'stock': 9,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'paper_lamp',
//       'leaf_lamp',
//       'brown',
//       'beige',
//       'warm',
//       'natural',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Saturn Planet Table Lamp',
//     'nameAR': 'مصباح طاولة كوكب زحل',
//     'description':
//         'A creative Saturn planet table lamp that adds a modern cosmic touch to desks and room corners.',
//     'descriptionAR':
//         'مصباح طاولة كوكب زحل إبداعي يضيف لمسة كونية حديثة للمكاتب وزوايا الغرف.',
//     'price': 760.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588990/p055_saturn_planet_table_lamp.jpg_dkx3ad.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'TqLQoWZAfawfkewvGD0X',
//     'stock': 6,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'planet_lamp',
//       'saturn_lamp',
//       'orange',
//       'brown',
//       'black',
//       'modern',
//       'office',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Moon Globe Table Lamp',
//     'nameAR': 'مصباح طاولة كرة القمر',
//     'description':
//         'A moon globe table lamp that creates soft calming light for bedrooms, desks, and relaxing spaces.',
//     'descriptionAR':
//         'مصباح طاولة كرة القمر يخلق إضاءة ناعمة هادئة لغرف النوم والمكاتب والمساحات المريحة.',
//     'price': 650.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588994/p056_moon_globe_table_lamp.jpg_kxr6of.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'buDpekfFigv5KzMfeyHq',
//     'stock': 11,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'moon_lamp',
//       'globe_lamp',
//       'white',
//       'beige',
//       'gold',
//       'calm',
//       'soft_light',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Mushroom Glow Table Lamp',
//     'nameAR': 'مصباح طاولة توهج فطر',
//     'description':
//         'A cozy mushroom glow table lamp that gives warm light and works well for bedside or reading corners.',
//     'descriptionAR':
//         'مصباح طاولة توهج فطر دافئ يعمل جيداً لجانب السرير أو زوايا القراءة.',
//     'price': 590.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777588999/p057_mushroom_glow_table_lamp.jpg_cxi7jl.jpg',
//     ],
//     'categoryId': 'handmade_lamps',
//     'sellerId': 'dE62YTlv5A86SSG3sg07',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'lamp',
//       'mushroom_lamp',
//       'glow_lamp',
//       'cream',
//       'beige',
//       'yellow',
//       'cozy',
//       'reading_corner',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Pink Crochet Handbag',
//     'nameAR': 'حقيبة يد كروشيه وردية',
//     'description':
//         'A handmade pink crochet handbag with floral details, suitable as a cute accessory or decorative handmade item.',
//     'descriptionAR':
//         'حقيبة يد كروشيه وردية يدوية بتفاصيل زهرية، مناسبة كإكسسوار لطيف أو قطعة ديكور يدوية.',
//     'price': 420.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777592935/p058_pink_crochet_handbag.jpg_o5lhw8.jpg',
//     ],
//     'categoryId': 'crochet_products',
//     'sellerId': 'gvik0mzRmKsHFBm6E4qq',
//     'stock': 9,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'crochet',
//       'handbag',
//       'bag',
//       'pink',
//       'white',
//       'green',
//       'cute',
//       'floral',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Crochet Sunflower Stem',
//     'nameAR': 'ساق عباد شمس كروشيه',
//     'description':
//         'A handmade crochet sunflower stem that adds a bright cheerful touch to desks, shelves, and small spaces.',
//     'descriptionAR':
//         'ساق عباد شمس كروشيه يدوية تضيف لمسة مشرقة مرحة للمكاتب والرفوف والمساحات الصغيرة.',
//     'price': 180.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777592935/p059_crochet_sunflower_stem.jpg_vc8gve.jpg',
//     ],
//     'categoryId': 'crochet_products',
//     'sellerId': 'hO5qdnh32hPNOeKD7piv0f6Vodf1',
//     'stock': 18,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.7,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'crochet',
//       'sunflower',
//       'flower',
//       'yellow',
//       'brown',
//       'green',
//       'cheerful',
//       'desk_decor',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Yellow Crochet Flower Bouquet',
//     'nameAR': 'باقة زهور كروشيه صفراء',
//     'description':
//         'A handmade yellow crochet flower bouquet, perfect as a long-lasting gift or bright room decoration.',
//     'descriptionAR':
//         'باقة زهور كروشيه صفراء يدوية، مثالية كهدية طويلة الأمد أو ديكور غرفة مشرق.',
//     'price': 450.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777592938/p060_yellow_crochet_flower_bouquet.jpg_qofvim.jpg',
//     ],
//     'categoryId': 'crochet_products',
//     'sellerId': 'hd9VKkCz5VUGI9Lq923D',
//     'stock': 10,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.8,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'crochet',
//       'flower_bouquet',
//       'yellow',
//       'white',
//       'green',
//       'cheerful',
//       'gift',
//       'floral',
//       'handmade',
//     ],
//   },
//   {
//     'name': 'Brown Crochet Hair Bow',
//     'nameAR': 'قوس شعر كروشيه بني',
//     'description':
//         'A handmade brown crochet hair bow that works as a cute accessory and small gift item.',
//     'descriptionAR':
//         'قوس شعر كروشيه بني يدوي يعمل كإكسسوار لطيف وقطعة هدايا صغيرة.',
//     'price': 130.0,
//     'discountedPrice': null,
//     'currency': 'EGP',
//     'images': [
//       'https://res.cloudinary.com/dw49vhf6h/image/upload/q_auto/f_auto/v1777593045/p088_brown_crochet_hair_bow.jpg_lrljrj.jpg',
//     ],
//     'categoryId': 'crochet_products',
//     'sellerId': 'knx1uE0jM0SoVCTwBFZKZQWJtj73',
//     'stock': 20,
//     'isActive': true,
//     'status': 'approved',
//     'rating': 4.6,
//     'reviewsCount': 0,
//     'salesCount': 0,
//     'tags': [
//       'crochet',
//       'hair_bow',
//       'brown',
//       'cute',
//       'accessory',
//       'kids_room',
//       'gift',
//       'handmade',
//     ],
//   },
// ];

// // 🔥 دالة رئيسية: رفع جميع المنتجات إلى Firestore
// Future<void> uploadProductsToFirestore() async {
//   final FirebaseFirestore firestore = FirebaseFirestore.instance;
//   final WriteBatch batch = firestore.batch();
//   final CollectionReference productsCollection = firestore.collection(
//     'products',
//   );
//   // Add each product to the batch
//   for (final Map<String, dynamic> product in productsData) {
//     final DocumentReference docRef = productsCollection
//         .doc(); // Auto-generates document ID
//     batch.set(docRef, product);
//   }
//   try {
//     await batch.commit();
//     print(
//       '✅ Successfully uploaded ${productsData.length} products to "products" collection',
//     );
//   } catch (e, stackTrace) {
//     print('❌ Failed to upload products: $e');
//     print('Stack trace: $stackTrace');
//   }
// }
